In [15]:
import pandas as pd
import scraper
import importlib
importlib.reload(scraper) # every run

In [16]:
df = scraper.getData()

In [18]:
df.columns = pd.MultiIndex.from_tuples(
    [('About' if 'Unnamed' in level_0 else level_0, level_1) 
        for level_0, level_1 in df.columns],
            names=df.columns.names
)
df.columns

MultiIndex([(         'About',   'Player'),
            (         'About',   'Nation'),
            (         'About',      'Pos'),
            (         'About',      'Age'),
            (         'About',       'MP'),
            (  'Playing Time',   'Starts'),
            (  'Playing Time',      'Min'),
            (  'Playing Time',      '90s'),
            (   'Performance',      'Gls'),
            (   'Performance',      'Ast'),
            (   'Performance',      'G+A'),
            (   'Performance',     'G-PK'),
            (   'Performance',       'PK'),
            (   'Performance',    'PKatt'),
            (   'Performance',     'CrdY'),
            (   'Performance',     'CrdR'),
            (      'Expected',       'xG'),
            (      'Expected',     'npxG'),
            (      'Expected',      'xAG'),
            (      'Expected', 'npxG+xAG'),
            (   'Progression',     'PrgC'),
            (   'Progression',     'PrgP'),
            (   'Progression',     'PrgR'),
            ('Per 90 Minutes',      'Gls'),
            ('Per 90 Minutes',      'Ast'),
            ('Per 90 Minutes',      'G+A'),
            ('Per 90 Minutes',     'G-PK'),
            ('Per 90 Minutes',   'G+A-PK'),
            ('Per 90 Minutes',       'xG'),
            ('Per 90 Minutes',      'xAG'),
            ('Per 90 Minutes',   'xG+xAG'),
            ('Per 90 Minutes',     'npxG'),
            ('Per 90 Minutes', 'npxG+xAG'),
            (         'About',  'Matches')],
           )

In [19]:
df['About']

                Player   Nation    Pos   Age  MP  Matches
0         David de Gea   es ESP     GK  31.0  38  Matches
1      Bruno Fernandes   pt POR  MF,FW  27.0  37  Matches
2      Marcus Rashford  eng ENG     FW  24.0  35  Matches
3            Luke Shaw  eng ENG     DF  27.0  31  Matches
4    Christian Eriksen   dk DEN     MF  30.0  28  Matches
5          Diogo Dalot   pt POR     DF  23.0  26  Matches
6             Casemiro   br BRA     MF  30.0  28  Matches
7    Lisandro Martínez   ar ARG     DF  24.0  27  Matches
8               Antony   br BRA     FW  22.0  25  Matches
9       Raphaël Varane   fr FRA     DF  29.0  24  Matches
10        Jadon Sancho  eng ENG  FW,MF  22.0  26  Matches
11   Aaron Wan-Bissaka  eng ENG     DF  24.0  19  Matches
12      Tyrell Malacia   nl NED     DF  22.0  22  Matches
13     Victor Lindelöf   se SWE     DF  28.0  20  Matches
14                Fred   br BRA     MF  29.0  35  Matches
15     Anthony Martial   fr FRA     FW  26.0  21  Matches
16     Scott McTominay  sct SCO     MF  25.0  24  Matches
17       Wout Weghorst   nl NED  FW,MF  29.0  17  Matches
18       Harry Maguire  eng ENG     DF  29.0  16  Matches
19     Marcel Sabitzer   at AUT     MF  28.0  11  Matches
20  Alejandro Garnacho   ar ARG  FW,MF  18.0  19  Matches
21      Anthony Elanga   se SWE     FW  20.0  16  Matches
22   Cristiano Ronaldo   pt POR     FW  37.0  10  Matches
23   Donny van de Beek   nl NED     MF  25.0   7  Matches
24   Facundo Pellistri   uy URU  FW,MF  20.0   4  Matches
25       Kobbie Mainoo  eng ENG     MF  17.0   1  Matches
26        Rhys Bennett  eng ENG     DF  18.0   0  Matches
27       Nathan Bishop  eng ENG     GK  22.0   0  Matches
28        Jack Butland  eng ENG     GK  29.0   0  Matches
29     Martin Dúbravka   sk SVK     GK  33.0   0  Matches
30        James Garner  eng ENG     MF  21.0   0  Matches
31          Tom Heaton  eng ENG     GK  36.0   0  Matches
32        Zidane Iqbal   iq IRQ     MF  19.0   0  Matches
33         Marc Jurado   es ESP     DF  18.0   0  Matches
34         Matej Kovar   cz CZE     GK  22.0   0  Matches
35     Shola Shoretire  eng ENG     MF  18.0   0  Matches
36    Brandon Williams  eng ENG     DF  21.0   0  Matches
37         Squad Total      NaN    NaN  26.9  38      NaN
38      Opponent Total      NaN    NaN  26.4  38      NaN

In [20]:
df['Playing Time']

    Starts     Min   90s
0       38  3420.0  38.0
1       37  3316.0  36.8
2       32  2879.0  32.0
3       30  2552.0  28.4
4       25  2048.0  22.8
5       24  2154.0  23.9
6       24  2124.0  23.6
7       24  2114.0  23.5
8       23  1802.0  20.0
9       22  1911.0  21.2
10      21  1686.0  18.7
11      16  1435.0  15.9
12      14  1396.0  15.5
13      14  1365.0  15.2
14      12  1249.0  13.9
15      11   978.0  10.9
16      10  1160.0  12.9
17      10   797.0   8.9
18       8   767.0   8.5
19       7   627.0   7.0
20       5   569.0   6.3
21       5   426.0   4.7
22       4   525.0   5.8
23       2   167.0   1.9
24       0    64.0   0.7
25       0    11.0   0.1
26       0     NaN   NaN
27       0     NaN   NaN
28       0     NaN   NaN
29       0     NaN   NaN
30       0     NaN   NaN
31       0     NaN   NaN
32       0     NaN   NaN
33       0     NaN   NaN
34       0     NaN   NaN
35       0     NaN   NaN
36       0     NaN   NaN
37     418  3420.0  38.0
38     418  3420.0  38.0

In [21]:
df['Performance']

     Gls   Ast   G+A  G-PK   PK  PKatt  CrdY  CrdR
0    0.0   0.0   0.0   0.0  0.0    0.0   0.0   0.0
1    8.0   8.0  16.0   6.0  2.0    2.0   6.0   0.0
2   17.0   5.0  22.0  17.0  0.0    0.0   2.0   0.0
3    1.0   2.0   3.0   1.0  0.0    0.0   8.0   0.0
4    1.0   8.0   9.0   1.0  0.0    0.0   3.0   0.0
5    1.0   2.0   3.0   1.0  0.0    0.0   6.0   0.0
6    4.0   3.0   7.0   4.0  0.0    0.0   7.0   2.0
7    1.0   0.0   1.0   1.0  0.0    0.0   6.0   0.0
8    4.0   2.0   6.0   4.0  0.0    0.0   5.0   0.0
9    0.0   0.0   0.0   0.0  0.0    0.0   1.0   0.0
10   6.0   3.0   9.0   6.0  0.0    0.0   0.0   0.0
11   0.0   0.0   0.0   0.0  0.0    0.0   2.0   0.0
12   0.0   0.0   0.0   0.0  0.0    0.0   6.0   0.0
13   0.0   0.0   0.0   0.0  0.0    0.0   1.0   0.0
14   2.0   2.0   4.0   2.0  0.0    0.0   6.0   0.0
15   6.0   2.0   8.0   5.0  1.0    1.0   0.0   0.0
16   1.0   0.0   1.0   1.0  0.0    0.0   8.0   0.0
17   0.0   1.0   1.0   0.0  0.0    0.0   1.0   0.0
18   0.0   0.0   0.0   0.0  0.0    0.0   4.0   0.0
19   0.0   1.0   1.0   0.0  0.0    0.0   1.0   0.0
20   3.0   2.0   5.0   3.0  0.0    0.0   3.0   0.0
21   0.0   1.0   1.0   0.0  0.0    0.0   0.0   0.0
22   1.0   0.0   1.0   1.0  0.0    0.0   2.0   0.0
23   0.0   0.0   0.0   0.0  0.0    0.0   0.0   0.0
24   0.0   0.0   0.0   0.0  0.0    0.0   0.0   0.0
25   0.0   0.0   0.0   0.0  0.0    0.0   0.0   0.0
26   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
27   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
28   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
29   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
30   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
31   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
32   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
33   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
34   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
35   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
36   NaN   NaN   NaN   NaN  NaN    NaN   NaN   NaN
37  56.0  42.0  98.0  53.0  3.0    3.0  78.0   2.0
38  42.0  28.0  70.0  40.0  2.0    3.0  50.0   0.0